### ISSUE TITLE
Brakes keyboard scroll via Vimium-FF plugin

### ISSUE THREAD

**Issue by 2tolik** [quinton-ashley/firefox-hide-scrollbars#21] opened 2018-10-22 08:45 UTC
Brakes keyboard scroll support for "keyboard ninja / vim-like" plugin
https://addons.mozilla.org/en-GB/firefox/addon/vimium-ff/

**Comment by quinton-ashley** [comment] 2018-10-22 21:04
duplicate of #18

**Closed as completed by quinton-ashley** 2018-10-22 21:04 UTC
